version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 5558465Ab
      POSTGRES_DB: people_crud
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d  # Критически важная строка!
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d people_crud"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 5558465Ab
      DB_NAME: people_crud
      DB_SSL_MODE: disable
    ports:
      - "8080:8080"

volumes:
  postgres_data: